### ISSUE TITLE
Is there a website or screenshots?

### ISSUE THREAD

**Issue by dillfrescott** [zlingapp/zvelte#4]
I'd love to take a look at your app!

**Comment by xcodian** [comment]
Hello, I'm glad to see your interest! Right now we haven't opened the app for public use, but progress is coming along nicely. It is still in its early phases and we have key features left to iron out, but we believe it could become something great.

Some screenshots of the client app (and some of these are a little bit out of date):

<a href="https://ibb.co/hf5RXJ3"><img src="https://i.ibb.co/PQpZTvq/Screenshot-2023-11-19-18-45-29.png" alt="Screenshot-2023-11-19-18-45-29" border="0"></a>
<a href="https://ibb.co/ZYyYd5F"><img src="https://i.ibb.co/Nmwmx5J/image.png" alt="image" border="0"></a>
<a href="https://ibb.co/D7RZq5v"><img src="https://i.ibb.co/ZhM0ZWF/image.png" alt="image" border="0"></a>
<a href="https://imgbb.com/"><img src="https://i.ibb.co/fStTBNg/image.png" alt="image" border="0"></a> 

Our HTTP API also has OpenAPI docs generated for it to make development easy.

<a href="https://ibb.co/Rg6ZGWB"><img src="https://i.ibb.co/YNdY4Gy/image.png" alt="image" border="0"></a>

Hope that helps!

**Comment by dillfrescott** [comment]
And the server is open source correct?

**Comment by xcodian** [comment]
Yes, see https://github.com/zlingapp/server for the repo where it's being maintained.

**Comment by dillfrescott** [comment]
Oooooo cool!
